### ISSUE TITLE
Additional parameter description allowed in create_repo api request

### ISSUE THREAD

**Issue by tradjincal** [Schweitzer-Engineering-Laboratories/bitbucketserver#1]
Hello,
For create_repo (and I guess for some other), the bitbucket API allow an additional field description which you can add in your payload dict in the file  bitbucketserver/bitbucketserver.py

BR
Pierrick

**Comment by JasonKempSEL** [comment]
Ah, the [API docs](https://docs.atlassian.com/bitbucket-server/rest/7.20.0/bitbucket-rest.html#idp175) didn't mention that the description is settable at create. Repo descriptions were added in BB 6.2, and much of this code predates that version (despite being newly open sourced). I just never updated it.

In the meantime, you can specify description at create by manually doing the request yourself with the library:

```python
create_uri = 'projects/PROJ/repos'
payload = {'name': 'Repo Name', 'scmId': 'git', 'forkable': True, 'public': False, 'description': 'Specifying a description'}
reponse = bb.conn.post(uri, json=payload)
```
To update an existing repo the URI would be `projects/PROJ/repos/repo-slug` with a payload of just the description key/value.

**Comment by tradjincal** [comment]
Thanks for the suggestion. I will try to update it on my side.
I have started to implement a similar module just before I find your repo which seems complete for me so I may come back with some question :smile:

**Comment by JasonKempSEL** [comment]
I pushed out a release v1.1.0, which includes the description parameter for creating/updating repos. Let me know if there are any issues with it.
