### ISSUE TITLE
Need help for use SettingsResource object

### ISSUE THREAD

**Issue by tradjincal** [Schweitzer-Engineering-Laboratories/bitbucketserver#3]
Hello,
I try to use the `repo_branch_permissions`method which return a `SettingsResource` object but I did not understand how to use it.
`SettingsResource` is just derivated from `BitbucketObject` but I am not sure which attribute should I access.
Any suggestion?

BR

**Comment by JasonKempSEL** [comment]
That method should probably be changed to just return a dict. However, like all `BitbucketObject` derivatives, the attributes are dynamic references to the items in the `obj._raw` dict, which is what Bitbucket returns from the API.

Branch permissions look like:
```python
{'id': 2933,
 'scope': {'type': 'REPOSITORY', 'resourceId': 2504},
 'type': 'pull-request-only',
 'matcher': {'id': 'refs/heads/master',
  'displayId': 'master',
  'type': {'id': 'BRANCH', 'name': 'Branch'},
  'active': True},
 'users': [],
 'groups': [],
 'accessKeys': []}
```
So `obj.type` and `obj.matcher.id` are probably useful attributes.

**Comment by tradjincal** [comment]
Thanks for your comment
